### ISSUE TITLE
Clock does not appear in popup.js

### ISSUE THREAD

**Issue by ab00a** [ab00a/clockforgooglechrome#25]
Error handling response: TypeError: Cannot read properties of null (reading 'height')
    at paintClock (chrome-extension://geiclgpckecamnaeopbafbpjnoaiokpk/js/popup.js:10:13)
    at updateClock (chrome-extension://geiclgpckecamnaeopbafbpjnoaiokpk/js/popup.js:112:3)
    at chrome-extension://geiclgpckecamnaeopbafbpjnoaiokpk/js/popup.js:161:5

**Comment by ab00a** [comment]
Correct typo cvsClockface to cvsClockFace

Also, add display: table to popup.css monthview-->table

**Comment by ab00a** [comment]
Fixed
